fail_fast: false
repos:
  - repo: local # https://github.com/natsunoyoru97/cpp-simple-database.git
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format
        language: system
        stages: [push]
        args: ["--style=Google"]
      #- id: oclint
      #- id: uncrustify
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        stages: [push]
      - id: cpplint
        name: cpplint
        entry: cpplint
        language: system
        stages: [push]
      #- id: include-what-you-use